// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/mangahub.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request messages
type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_api_mangahub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{0}
}

func (x *GetMangaRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type ListMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangaRequest) Reset() {
	*x = ListMangaRequest{}
	mi := &file_api_mangahub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaRequest) ProtoMessage() {}

func (x *ListMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaRequest.ProtoReflect.Descriptor instead.
func (*ListMangaRequest) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{1}
}

func (x *ListMangaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMangaRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMangaRequest) Reset() {
	*x = SearchMangaRequest{}
	mi := &file_api_mangahub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMangaRequest) ProtoMessage() {}

func (x *SearchMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMangaRequest.ProtoReflect.Descriptor instead.
func (*SearchMangaRequest) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMangaRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	mi := &file_api_mangahub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type UpdateProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Chapter       int32                  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_api_mangahub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *UpdateProgressRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

// Response messages
type MangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaResponse) Reset() {
	*x = MangaResponse{}
	mi := &file_api_mangahub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaResponse) ProtoMessage() {}

func (x *MangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaResponse.ProtoReflect.Descriptor instead.
func (*MangaResponse) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{5}
}

func (x *MangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type ListMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mangas        []*Manga               `protobuf:"bytes,1,rep,name=mangas,proto3" json:"mangas,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangaResponse) Reset() {
	*x = ListMangaResponse{}
	mi := &file_api_mangahub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaResponse) ProtoMessage() {}

func (x *ListMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaResponse.ProtoReflect.Descriptor instead.
func (*ListMangaResponse) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{6}
}

func (x *ListMangaResponse) GetMangas() []*Manga {
	if x != nil {
		return x.Mangas
	}
	return nil
}

func (x *ListMangaResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *UserProgress          `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProgressResponse) Reset() {
	*x = UserProgressResponse{}
	mi := &file_api_mangahub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgressResponse) ProtoMessage() {}

func (x *UserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgressResponse.ProtoReflect.Descriptor instead.
func (*UserProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{7}
}

func (x *UserProgressResponse) GetProgress() *UserProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type UpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Progress      *UserProgress          `protobuf:"bytes,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_api_mangahub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateProgressResponse) GetProgress() *UserProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

// Data models
type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,6,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,8,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_api_mangahub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{9}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type UserProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,3,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Chapter       int32                  `protobuf:"varint,4,opt,name=chapter,proto3" json:"chapter,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProgress) Reset() {
	*x = UserProgress{}
	mi := &file_api_mangahub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgress) ProtoMessage() {}

func (x *UserProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_mangahub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgress.ProtoReflect.Descriptor instead.
func (*UserProgress) Descriptor() ([]byte, []int) {
	return file_api_mangahub_proto_rawDescGZIP(), []int{10}
}

func (x *UserProgress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgress) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *UserProgress) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *UserProgress) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_mangahub_proto protoreflect.FileDescriptor

const file_api_mangahub_proto_rawDesc = "" +
	"\n" +
	"\x12api/mangahub.proto\x12\bmangahub\",\n" +
	"\x0fGetMangaRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\"C\n" +
	"\x10ListMangaRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"*\n" +
	"\x12SearchMangaRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"L\n" +
	"\x16GetUserProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\"e\n" +
	"\x15UpdateProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x18\n" +
	"\achapter\x18\x03 \x01(\x05R\achapter\"6\n" +
	"\rMangaResponse\x12%\n" +
	"\x05manga\x18\x01 \x01(\v2\x0f.mangahub.MangaR\x05manga\"R\n" +
	"\x11ListMangaResponse\x12'\n" +
	"\x06mangas\x18\x01 \x03(\v2\x0f.mangahub.MangaR\x06mangas\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"J\n" +
	"\x14UserProgressResponse\x122\n" +
	"\bprogress\x18\x01 \x01(\v2\x16.mangahub.UserProgressR\bprogress\"\x80\x01\n" +
	"\x16UpdateProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\bprogress\x18\x03 \x01(\v2\x16.mangahub.UserProgressR\bprogress\"\xdb\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\x06 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\b \x01(\tR\bcoverUrl\"\x8b\x01\n" +
	"\fUserProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x03 \x01(\tR\amangaId\x12\x18\n" +
	"\achapter\x18\x04 \x01(\x05R\achapter\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt2\x88\x03\n" +
	"\fMangaService\x12>\n" +
	"\bGetManga\x12\x19.mangahub.GetMangaRequest\x1a\x17.mangahub.MangaResponse\x12D\n" +
	"\tListManga\x12\x1a.mangahub.ListMangaRequest\x1a\x1b.mangahub.ListMangaResponse\x12H\n" +
	"\vSearchManga\x12\x1c.mangahub.SearchMangaRequest\x1a\x1b.mangahub.ListMangaResponse\x12S\n" +
	"\x0fGetUserProgress\x12 .mangahub.GetUserProgressRequest\x1a\x1e.mangahub.UserProgressResponse\x12S\n" +
	"\x0eUpdateProgress\x12\x1f.mangahub.UpdateProgressRequest\x1a .mangahub.UpdateProgressResponseB\x0eZ\fmangahub/apib\x06proto3"

var (
	file_api_mangahub_proto_rawDescOnce sync.Once
	file_api_mangahub_proto_rawDescData []byte
)

func file_api_mangahub_proto_rawDescGZIP() []byte {
	file_api_mangahub_proto_rawDescOnce.Do(func() {
		file_api_mangahub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mangahub_proto_rawDesc), len(file_api_mangahub_proto_rawDesc)))
	})
	return file_api_mangahub_proto_rawDescData
}

var file_api_mangahub_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_mangahub_proto_goTypes = []any{
	(*GetMangaRequest)(nil),        // 0: mangahub.GetMangaRequest
	(*ListMangaRequest)(nil),       // 1: mangahub.ListMangaRequest
	(*SearchMangaRequest)(nil),     // 2: mangahub.SearchMangaRequest
	(*GetUserProgressRequest)(nil), // 3: mangahub.GetUserProgressRequest
	(*UpdateProgressRequest)(nil),  // 4: mangahub.UpdateProgressRequest
	(*MangaResponse)(nil),          // 5: mangahub.MangaResponse
	(*ListMangaResponse)(nil),      // 6: mangahub.ListMangaResponse
	(*UserProgressResponse)(nil),   // 7: mangahub.UserProgressResponse
	(*UpdateProgressResponse)(nil), // 8: mangahub.UpdateProgressResponse
	(*Manga)(nil),                  // 9: mangahub.Manga
	(*UserProgress)(nil),           // 10: mangahub.UserProgress
}
var file_api_mangahub_proto_depIdxs = []int32{
	9,  // 0: mangahub.MangaResponse.manga:type_name -> mangahub.Manga
	9,  // 1: mangahub.ListMangaResponse.mangas:type_name -> mangahub.Manga
	10, // 2: mangahub.UserProgressResponse.progress:type_name -> mangahub.UserProgress
	10, // 3: mangahub.UpdateProgressResponse.progress:type_name -> mangahub.UserProgress
	0,  // 4: mangahub.MangaService.GetManga:input_type -> mangahub.GetMangaRequest
	1,  // 5: mangahub.MangaService.ListManga:input_type -> mangahub.ListMangaRequest
	2,  // 6: mangahub.MangaService.SearchManga:input_type -> mangahub.SearchMangaRequest
	3,  // 7: mangahub.MangaService.GetUserProgress:input_type -> mangahub.GetUserProgressRequest
	4,  // 8: mangahub.MangaService.UpdateProgress:input_type -> mangahub.UpdateProgressRequest
	5,  // 9: mangahub.MangaService.GetManga:output_type -> mangahub.MangaResponse
	6,  // 10: mangahub.MangaService.ListManga:output_type -> mangahub.ListMangaResponse
	6,  // 11: mangahub.MangaService.SearchManga:output_type -> mangahub.ListMangaResponse
	7,  // 12: mangahub.MangaService.GetUserProgress:output_type -> mangahub.UserProgressResponse
	8,  // 13: mangahub.MangaService.UpdateProgress:output_type -> mangahub.UpdateProgressResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_mangahub_proto_init() }
func file_api_mangahub_proto_init() {
	if File_api_mangahub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mangahub_proto_rawDesc), len(file_api_mangahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mangahub_proto_goTypes,
		DependencyIndexes: file_api_mangahub_proto_depIdxs,
		MessageInfos:      file_api_mangahub_proto_msgTypes,
	}.Build()
	File_api_mangahub_proto = out.File
	file_api_mangahub_proto_goTypes = nil
	file_api_mangahub_proto_depIdxs = nil
}
